name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWD }}
    - name: Build the Docker image
      run: |
       docker build -t ${IMAGE_TAG} -f Dockerfile .
       docker push ${IMAGE_TAG}
      env:
        OPTEE_VERSION: 3.20.0
        IMAGE_TAG: worstass/optee-rs-dev:3.20.0
